name: Deploy to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Deploy to Hugging Face Spaces
        uses: huggingface/transformers-hub-deploy-action@main
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: Getaye/social-media-addiction-analyzer
          repo_type: space
          space_sdk: streamlit
          working_directory: ./
